on:
  workflow_call:
    inputs:
      username:
        description: 'A username passed from the caller workflow'
        default: 'john-doe'
        required: false
        type: string

jobs:
  reusable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print the input name to STDOUT
        run: echo 'Hello'
